### ISSUE TITLE
__class__ is not available

### ISSUE THREAD

**Issue by KOLANICH** [graalvm/graalpython#40] opened 2019-01-21 16:51 UTC
```python
class A:
   def b(self):
      return __class__()
```

**Comment by timfel** [comment] 2019-01-22 07:51
Interesting, I'd never see that pattern. `self.__class__()` works, obviously, but we don't set the `__class__` cell correctly, it appears.

**Comment by KOLANICH** [comment] 2019-01-22 08:34
`self.__class__` is the actual class
`__class__` is the class in which member the stuff is defined

```python
class A:
    def a(self):
        print(__class__, self.__class__)
class B(A):
   def b(self):
        print(__class__, self.__class__) #B, B
        self.a() # A, B
B().b()
```

**Comment by timfel** [comment] 2019-01-22 10:44
Yes, indeed :-)
As I said, the issue is that we don't set the `__class__` cell in the class definition function scope

**Comment by cosminbasca** [comment] 2019-01-24 10:51
Issue has been resolved, `__class__` cell var is set correctly in the function definition scope

**Comment by timfel** [comment] 2019-02-04 22:06
This fix is included in rc12

**Closed by timfel** 2019-02-04 22:06 UTC

**Comment by KOLANICH** [comment] 2019-02-07 17:00
Works. Thank you.
