### ISSUE TITLE
Type annotations and typed fields in data classes not parseable

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#38] opened 2019-01-20 10:08 UTC
Hi,

I know `dataclasses`  is not yet implemented but the following unittest fails with runtime exception
while CPython 3.6 simply returns without error.

```
import unittest


class DataClassesTests(unittest.TestCase):
    def test_dataclasses(self):
        try:
            from dataclasses import dataclass
        except ImportError:
            return

        @dataclass
        class Point:
            x: float
            y: float

        def f(x):
            return x


        self.assertEqual(f(Point(1, 2)), Point(1, 2))
```

`graalpython ./test_dataclass.py`

```
java.lang.RuntimeException: not implemented
	at com.oracle.graal.python.parser.AssignmentTranslator.translate(AssignmentTranslator.java:76)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitExpr_stmt(PythonTreeTranslator.java:1313)
	at com.oracle.graal.python.parser.antlr.Python3Parser$Expr_stmtContext.accept(Python3Parser.java:2132)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:155)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitSmall_stmt(Python3BaseVisitor.java:196)
	at com.oracle.graal.python.parser.antlr.Python3Parser$Small_stmtContext.accept(Python3Parser.java:1997)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:162)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitSimple_stmt(Python3BaseVisitor.java:189)
	at com.oracle.graal.python.parser.antlr.Python3Parser$Simple_stmtContext.accept(Python3Parser.java:1900)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:155)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitStmt(Python3BaseVisitor.java:182)
	at com.oracle.graal.python.parser.antlr.Python3Parser$StmtContext.accept(Python3Parser.java:1801)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:162)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitSuite(Python3BaseVisitor.java:434)
	at com.oracle.graal.python.parser.antlr.Python3Parser$SuiteContext.accept(Python3Parser.java:4569)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitClassdef(PythonTreeTranslator.java:1764)
	at com.oracle.graal.python.parser.antlr.Python3Parser$ClassdefContext.accept(Python3Parser.java:7443)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitDecorated(PythonTreeTranslator.java:910)
	at com.oracle.graal.python.parser.antlr.Python3Parser$DecoratedContext.accept(Python3Parser.java:649)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:155)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitCompound_stmt(Python3BaseVisitor.java:371)
	at com.oracle.graal.python.parser.antlr.Python3Parser$Compound_stmtContext.accept(Python3Parser.java:3807)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:155)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitStmt(Python3BaseVisitor.java:182)
	at com.oracle.graal.python.parser.antlr.Python3Parser$StmtContext.accept(Python3Parser.java:1801)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:162)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitSuite(Python3BaseVisitor.java:434)
	at com.oracle.graal.python.parser.antlr.Python3Parser$SuiteContext.accept(Python3Parser.java:4569)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitFuncdef(PythonTreeTranslator.java:1485)
	at com.oracle.graal.python.parser.antlr.Python3Parser$FuncdefContext.accept(Python3Parser.java:772)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:155)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitCompound_stmt(Python3BaseVisitor.java:371)
	at com.oracle.graal.python.parser.antlr.Python3Parser$Compound_stmtContext.accept(Python3Parser.java:3807)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:155)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitStmt(Python3BaseVisitor.java:182)
	at com.oracle.graal.python.parser.antlr.Python3Parser$StmtContext.accept(Python3Parser.java:1801)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:162)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitSuite(Python3BaseVisitor.java:434)
	at com.oracle.graal.python.parser.antlr.Python3Parser$SuiteContext.accept(Python3Parser.java:4569)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitClassdef(PythonTreeTranslator.java:1764)
	at com.oracle.graal.python.parser.antlr.Python3Parser$ClassdefContext.accept(Python3Parser.java:7443)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:155)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitCompound_stmt(Python3BaseVisitor.java:371)
	at com.oracle.graal.python.parser.antlr.Python3Parser$Compound_stmtContext.accept(Python3Parser.java:3807)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:155)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitStmt(Python3BaseVisitor.java:182)
	at com.oracle.graal.python.parser.antlr.Python3Parser$StmtContext.accept(Python3Parser.java:1801)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitChildren(PythonTreeTranslator.java:162)
	at com.oracle.graal.python.parser.antlr.Python3BaseVisitor.visitFile_input(Python3BaseVisitor.java:56)
	at com.oracle.graal.python.parser.PythonTreeTranslator.visitFile_input(PythonTreeTranslator.java:232)
	at com.oracle.graal.python.parser.antlr.Python3Parser$File_inputContext.accept(Python3Parser.java:328)
	at com.oracle.graal.python.parser.PythonTreeTranslator.translate(PythonTreeTranslator.java:133)
	at com.oracle.graal.python.parser.PythonParserImpl.parse(PythonParserImpl.java:101)
	at com.oracle.graal.python.PythonLanguage.doParse(PythonLanguage.java:245)
	at com.oracle.graal.python.PythonLanguage.parse(PythonLanguage.java:235)
	at com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:798)
	at com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1233)
	at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.parse(TruffleLanguage.java:2413)
	at com.oracle.truffle.polyglot.PolyglotSourceCache.parseImpl(PolyglotSourceCache.java:92)
	at com.oracle.truffle.polyglot.PolyglotSourceCache.parseCached(PolyglotSourceCache.java:73)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:186)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:751)
	at org.graalvm.polyglot.Context.eval(Context.java:335)
	at com.oracle.graal.python.shell.GraalPythonMain.evalNonInteractive(GraalPythonMain.java:356)
	at com.oracle.graal.python.shell.GraalPythonMain.launch(GraalPythonMain.java:280)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:132)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:72)
	at com.oracle.graal.python.shell.GraalPythonMain.main(GraalPythonMain.java:56)
Traceback (most recent call last):
java.lang.RuntimeException: Failed in com.oracle.graal.python.parser.PythonTreeTranslator@7fac575914a8 with error java.lang.RuntimeException: not implemented
```

**Comment by timfel** [comment] 2019-01-21 08:48
The problem is that type annotations are not implemented in our parser, so this fails at the parsing stage, before anything is run

**Comment by kontrafiktion** [comment] 2019-01-22 10:54
Is that something you would want help from the outside, or are you still in "internal development mode" (with public visibility)

**Comment by timfel** [comment] 2019-01-22 12:45
We're happy to accept contributions already :)

**Comment by oroppas** [comment] 2019-11-08 12:02
Is type annotation implemented already?

**Comment by timfel** [comment] 2019-11-08 12:42
@ppisl recently implemented and merged support for annotations to master

**Closed** 2019-11-08 13:58 UTC
