### ISSUE TITLE
[_functools]: TypeError: __init__() missing 1 required positional argument: 'iterable'

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#62] opened 2019-02-28 11:21 UTC
I tried to use toolz and got the 

```
Traceback (most recent call last):
  File "wordcount.py", line 8, in <module 'wordcount.py'>
    wordcount = compose(frequencies, map(stem), str.split)
  File "functoolz.py", line 284, in __call__
    return self._partial(*args, **kwargs)
  File "_functools", line 57, in newfunc
TypeError: __init__() missing 1 required positional argument: 'iterable'
```

**Comment by fangerer** [comment] 2019-06-27 08:42
Hi Ryuta,

sorry for not commenting on this issue for such a long time and thanks for reporting it.
I'm able to reproduce the problem and will investigate the cause.

- Florian

**Comment by fangerer** [comment] 2019-06-28 06:25
This problem is fixed in master and I could successfully import `toolz`.

**Closed by fangerer** 2019-06-28 06:25 UTC
Labels: bug

**Comment by oroppas** [comment] 2019-06-30 05:15
Hi Florian, I confirm the fix work. Thank you!
